# redis-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
    serviceName: "redis"
    replicas: 3
    selector:
      matchLabels:
        app: redis
    template:
      metadata:
        labels:
          app: redis
      spec:
        containers:
          - name: redis
            image: redis:7.2
            ports:
              - containerPort: 6379
            args: ["redis-server", "/etc/redis/redis.conf"]
          - name: redis-exporter
            image: oliver006/redis_exporter:v1.61.0
            ports:
              - containerPort: 9121
            env:
              - name: REDIS_ADDR
                value: "redis://localhost:6379"
              - name: REDIS_EXPORTER_WEB_LISTEN_ADDRESS
                value: ":9121"
            volumeMounts:
              - name: redis-data
                mountPath: /data
              - name: redis-config-volume
                mountPath: /etc/redis
                readOnly: true
        volumes:
          - name: redis-config-volume
            configMap:
              name: redis-config
    volumeClaimTemplates:
      - metadata:
          name: redis-data
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi